name: sencare_patientapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/image.png
dependency_overrides:
  analyzer: ^6.2.0

